name: CI

# Trigger the workflow on push to main, or on pull request
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: "Test the update-gh-pages action"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: "gap-actions/ActionTestGAPDocPackage"
          - package: "gap-actions/ActionTestOldDocPackage"
    steps:
      # the order of the checkout actions is important because all contents of
      # the target folder of the checkout action is removed
      - name: "Clone the package"
        uses: actions/checkout@v6
        with:
          repository: ${{ matrix.package }}

      - name: "Check out this repository"
        uses: actions/checkout@v6
        with:
          path: .this-action/

      - name: "Setup GAP"
        uses: gap-actions/setup-gap@v3
          
      - name: "Build the GitHub pages"
        uses: ./.this-action/
        with:
          dry-run: true
          repository: ${{ matrix.package }}
          extra-files: "CHANGES.md:copied_files/CHANGELOG.md,tst/:copied_files/test_files,tst,CHANGES.md"
